dependencies {

    api project(":support-logging-core")

    implementation platform("org.springframework.boot:spring-boot-dependencies:${springVersion3}")
    testImplementation platform("org.springframework.boot:spring-boot-dependencies:${springVersion3}")
    annotationProcessor platform("org.springframework.boot:spring-boot-dependencies:${springVersion3}")

    implementation "org.springframework.boot:spring-boot"
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "com.fasterxml.jackson.core:jackson-databind"

    api "org.springframework.boot:spring-boot-starter-aop"
    api "io.projectreactor:reactor-core"

    annotationProcessor "org.springframework.boot:spring-boot-configuration-processor"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.projectreactor:reactor-test"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}